// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.migration
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241017094425_updateRaisedDateSeedData")]
    partial class updateRaisedDateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscussionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerFileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Application Bug"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Network Issue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User Issue"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("Domain.Entities.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpectedDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedDays = 14,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            ExpectedDays = 7,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            ExpectedDays = 1,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product 3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RaisedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RaisedBy");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "Description for ticket 2",
                            ExpectedDate = new DateTime(2024, 5, 1, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(3916),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(3916),
                            Status = "NEW",
                            Summary = "Sample ticket 2"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(5899),
                            Description = "Description for ticket 3",
                            ExpectedDate = new DateTime(2024, 6, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(5899),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(5899),
                            Status = "CLOSED",
                            Summary = "Sample ticket 3"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Description for ticket 4",
                            ExpectedDate = new DateTime(2024, 9, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(5985),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 9, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(5985),
                            Status = "OPEN",
                            Summary = "Sample ticket 4"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Description for ticket 5",
                            ExpectedDate = new DateTime(2024, 5, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6003),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6003),
                            Status = "OPEN",
                            Summary = "Sample ticket 5"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 7, 8, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6016),
                            Description = "Description for ticket 6",
                            ExpectedDate = new DateTime(2024, 7, 8, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6016),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6016),
                            Status = "CLOSED",
                            Summary = "Sample ticket 6"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 7, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6029),
                            Description = "Description for ticket 7",
                            ExpectedDate = new DateTime(2024, 7, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6029),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6029),
                            Status = "CLOSED",
                            Summary = "Sample ticket 7"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 5, 29, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6042),
                            Description = "Description for ticket 8",
                            ExpectedDate = new DateTime(2024, 5, 29, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6042),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 28, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6042),
                            Status = "CLOSED",
                            Summary = "Sample ticket 8"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Description for ticket 9",
                            ExpectedDate = new DateTime(2024, 5, 21, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6054),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 20, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6054),
                            Status = "OPEN",
                            Summary = "Sample ticket 9"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Description for ticket 10",
                            ExpectedDate = new DateTime(2024, 2, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6067),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 2, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6067),
                            Status = "NEW",
                            Summary = "Sample ticket 10"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Description for ticket 11",
                            ExpectedDate = new DateTime(2024, 1, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6080),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 1, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6080),
                            Status = "NEW",
                            Summary = "Sample ticket 11"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Description for ticket 12",
                            ExpectedDate = new DateTime(2024, 8, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6091),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 8, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6091),
                            Status = "NEW",
                            Summary = "Sample ticket 12"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Description for ticket 13",
                            ExpectedDate = new DateTime(2024, 2, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6130),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 2, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6130),
                            Status = "NEW",
                            Summary = "Sample ticket 13"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 2, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6143),
                            Description = "Description for ticket 14",
                            ExpectedDate = new DateTime(2024, 2, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6143),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 2, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6143),
                            Status = "CLOSED",
                            Summary = "Sample ticket 14"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Description for ticket 15",
                            ExpectedDate = new DateTime(2024, 9, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6155),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 8, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6155),
                            Status = "OPEN",
                            Summary = "Sample ticket 15"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Description for ticket 16",
                            ExpectedDate = new DateTime(2024, 4, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6166),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 4, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6166),
                            Status = "NEW",
                            Summary = "Sample ticket 16"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 3, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6178),
                            Description = "Description for ticket 17",
                            ExpectedDate = new DateTime(2024, 3, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6178),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 4, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6178),
                            Status = "CLOSED",
                            Summary = "Sample ticket 17"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6191),
                            Description = "Description for ticket 18",
                            ExpectedDate = new DateTime(2024, 6, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6191),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6191),
                            Status = "CLOSED",
                            Summary = "Sample ticket 18"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6203),
                            Description = "Description for ticket 19",
                            ExpectedDate = new DateTime(2024, 6, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6203),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6203),
                            Status = "CLOSED",
                            Summary = "Sample ticket 19"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Description for ticket 20",
                            ExpectedDate = new DateTime(2024, 9, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6215),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 9, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6215),
                            Status = "NEW",
                            Summary = "Sample ticket 20"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 10, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6227),
                            Description = "Description for ticket 21",
                            ExpectedDate = new DateTime(2024, 10, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6227),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 10, 4, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6227),
                            Status = "CLOSED",
                            Summary = "Sample ticket 21"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Description for ticket 22",
                            ExpectedDate = new DateTime(2024, 10, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6254),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 10, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6254),
                            Status = "OPEN",
                            Summary = "Sample ticket 22"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 3, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6267),
                            Description = "Description for ticket 23",
                            ExpectedDate = new DateTime(2024, 3, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6267),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6267),
                            Status = "CLOSED",
                            Summary = "Sample ticket 23"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "Description for ticket 24",
                            ExpectedDate = new DateTime(2024, 8, 14, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6279),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 8, 13, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6279),
                            Status = "NEW",
                            Summary = "Sample ticket 24"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 4, 21, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6291),
                            Description = "Description for ticket 25",
                            ExpectedDate = new DateTime(2024, 4, 21, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6291),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 20, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6291),
                            Status = "CLOSED",
                            Summary = "Sample ticket 25"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 1, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6303),
                            Description = "Description for ticket 26",
                            ExpectedDate = new DateTime(2024, 1, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6303),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 1, 8, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6303),
                            Status = "CLOSED",
                            Summary = "Sample ticket 26"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6315),
                            Description = "Description for ticket 27",
                            ExpectedDate = new DateTime(2024, 6, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6315),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6315),
                            Status = "CLOSED",
                            Summary = "Sample ticket 27"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "Description for ticket 28",
                            ExpectedDate = new DateTime(2024, 4, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6327),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6327),
                            Status = "OPEN",
                            Summary = "Sample ticket 28"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 13, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6338),
                            Description = "Description for ticket 29",
                            ExpectedDate = new DateTime(2024, 6, 13, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6338),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 6, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6338),
                            Status = "CLOSED",
                            Summary = "Sample ticket 29"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 5, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6350),
                            Description = "Description for ticket 30",
                            ExpectedDate = new DateTime(2024, 5, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6350),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 21, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6350),
                            Status = "CLOSED",
                            Summary = "Sample ticket 30"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 5, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6405),
                            Description = "Description for ticket 31",
                            ExpectedDate = new DateTime(2024, 5, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6405),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 4, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6405),
                            Status = "CLOSED",
                            Summary = "Sample ticket 31"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "Description for ticket 32",
                            ExpectedDate = new DateTime(2024, 9, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6418),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 9, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6418),
                            Status = "NEW",
                            Summary = "Sample ticket 32"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 3, 23, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6430),
                            Description = "Description for ticket 33",
                            ExpectedDate = new DateTime(2024, 3, 23, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6430),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6430),
                            Status = "CLOSED",
                            Summary = "Sample ticket 33"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Description for ticket 34",
                            ExpectedDate = new DateTime(2024, 9, 6, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6442),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 8, 23, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6442),
                            Status = "OPEN",
                            Summary = "Sample ticket 34"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "Description for ticket 35",
                            ExpectedDate = new DateTime(2024, 6, 14, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6453),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 7, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6453),
                            Status = "NEW",
                            Summary = "Sample ticket 35"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Description for ticket 36",
                            ExpectedDate = new DateTime(2024, 3, 6, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6465),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 2, 28, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6465),
                            Status = "NEW",
                            Summary = "Sample ticket 36"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "Description for ticket 37",
                            ExpectedDate = new DateTime(2024, 7, 6, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6477),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 29, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6477),
                            Status = "NEW",
                            Summary = "Sample ticket 37"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 3, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6488),
                            Description = "Description for ticket 38",
                            ExpectedDate = new DateTime(2024, 3, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6488),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6488),
                            Status = "CLOSED",
                            Summary = "Sample ticket 38"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 3,
                            Description = "Description for ticket 39",
                            ExpectedDate = new DateTime(2024, 4, 11, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6501),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 28, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6501),
                            Status = "OPEN",
                            Summary = "Sample ticket 39"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Description for ticket 40",
                            ExpectedDate = new DateTime(2024, 7, 23, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6542),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6542),
                            Status = "NEW",
                            Summary = "Sample ticket 40"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Description = "Description for ticket 41",
                            ExpectedDate = new DateTime(2024, 5, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6554),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6554),
                            Status = "NEW",
                            Summary = "Sample ticket 41"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 7, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6566),
                            Description = "Description for ticket 42",
                            ExpectedDate = new DateTime(2024, 7, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6566),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6566),
                            Status = "CLOSED",
                            Summary = "Sample ticket 42"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 7, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6578),
                            Description = "Description for ticket 43",
                            ExpectedDate = new DateTime(2024, 7, 22, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6578),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 21, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6578),
                            Status = "CLOSED",
                            Summary = "Sample ticket 43"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Description = "Description for ticket 44",
                            ExpectedDate = new DateTime(2024, 8, 27, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6590),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 8, 20, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6590),
                            Status = "OPEN",
                            Summary = "Sample ticket 44"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Description = "Description for ticket 45",
                            ExpectedDate = new DateTime(2024, 1, 23, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6602),
                            PriorityId = 1,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 1, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6602),
                            Status = "NEW",
                            Summary = "Sample ticket 45"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Description = "Description for ticket 46",
                            ExpectedDate = new DateTime(2024, 6, 14, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6613),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 31, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6613),
                            Status = "OPEN",
                            Summary = "Sample ticket 46"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 5, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6625),
                            Description = "Description for ticket 47",
                            ExpectedDate = new DateTime(2024, 5, 25, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6625),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6625),
                            Status = "CLOSED",
                            Summary = "Sample ticket 47"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            Description = "Description for ticket 48",
                            ExpectedDate = new DateTime(2024, 9, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6638),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 9, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6638),
                            Status = "OPEN",
                            Summary = "Sample ticket 48"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            Description = "Description for ticket 49",
                            ExpectedDate = new DateTime(2024, 10, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6673),
                            PriorityId = 2,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 10, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6673),
                            Status = "OPEN",
                            Summary = "Sample ticket 49"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 3,
                            Description = "Description for ticket 50",
                            ExpectedDate = new DateTime(2024, 5, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6685),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 2, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6685),
                            Status = "NEW",
                            Summary = "Sample ticket 50"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 3,
                            Description = "Description for ticket 51",
                            ExpectedDate = new DateTime(2024, 1, 26, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6697),
                            PriorityId = 3,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 1, 12, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6697),
                            Status = "OPEN",
                            Summary = "Sample ticket 51"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            Description = "Description for ticket 52",
                            ExpectedDate = new DateTime(2024, 3, 20, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6709),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 13, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6709),
                            Status = "NEW",
                            Summary = "Sample ticket 52"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 2,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 6, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6720),
                            Description = "Description for ticket 53",
                            ExpectedDate = new DateTime(2024, 6, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6720),
                            PriorityId = 3,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 4, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6720),
                            Status = "CLOSED",
                            Summary = "Sample ticket 53"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            Description = "Description for ticket 54",
                            ExpectedDate = new DateTime(2024, 10, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6733),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 10, 3, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6733),
                            Status = "OPEN",
                            Summary = "Sample ticket 54"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 3,
                            Description = "Description for ticket 55",
                            ExpectedDate = new DateTime(2024, 6, 11, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6745),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6745),
                            Status = "NEW",
                            Summary = "Sample ticket 55"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            Description = "Description for ticket 56",
                            ExpectedDate = new DateTime(2024, 7, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6757),
                            PriorityId = 1,
                            ProductId = 2,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6757),
                            Status = "NEW",
                            Summary = "Sample ticket 56"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 3,
                            ClosedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            ClosedDate = new DateTime(2024, 3, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6795),
                            Description = "Description for ticket 57",
                            ExpectedDate = new DateTime(2024, 3, 18, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6795),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 3, 11, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6795),
                            Status = "CLOSED",
                            Summary = "Sample ticket 57"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            Description = "Description for ticket 58",
                            ExpectedDate = new DateTime(2024, 5, 5, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6810),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 5, 4, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6810),
                            Status = "OPEN",
                            Summary = "Sample ticket 58"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 1,
                            Description = "Description for ticket 59",
                            ExpectedDate = new DateTime(2024, 7, 9, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6821),
                            PriorityId = 2,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 7, 8, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6821),
                            Status = "OPEN",
                            Summary = "Sample ticket 59"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 3,
                            Description = "Description for ticket 60",
                            ExpectedDate = new DateTime(2024, 9, 24, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6833),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 9, 10, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6833),
                            Status = "NEW",
                            Summary = "Sample ticket 60"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            Description = "Description for ticket 61",
                            ExpectedDate = new DateTime(2024, 6, 17, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6844),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            RaisedDate = new DateTime(2024, 6, 16, 11, 44, 25, 225, DateTimeKind.Unspecified).AddTicks(6844),
                            Status = "OPEN",
                            Summary = "Sample ticket 61"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccountConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c5e57a7f-39e8-4007-940e-4468dfbb04f3",
                            AccessFailedCount = 0,
                            AccountConfirmed = false,
                            ConcurrencyStamp = "04ab4d49-0693-40f2-b361-f18d7d45ef88",
                            Email = "test@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@GMAIL.COM",
                            NormalizedUserName = "TEST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH+XNJ52O8wW/bXpoO9CUO/Fprl8AnZUhO70sOd0yWJY0umgtY66o9A3I3aQua62/Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a67d869d-6eb9-4aaa-89d4-eb04a8140c24",
                            TwoFactorEnabled = false,
                            UserName = "test@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Domain.Entities.Discussion", "Discussion")
                        .WithMany("Attachments")
                        .HasForeignKey("DiscussionId");

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId");

                    b.Navigation("Discussion");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
